//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JournalTrace.Language.Localization {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class pt {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal pt() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JournalTrace.Language.Localization.pt", typeof(pt).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Limpar.
        /// </summary>
        internal static string clear {
            get {
                return ResourceManager.GetString("clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Copiar.
        /// </summary>
        internal static string copy {
            get {
                return ResourceManager.GetString("copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Quantidade de entradas:.
        /// </summary>
        internal static string countall {
            get {
                return ResourceManager.GetString("countall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Diretórios:.
        /// </summary>
        internal static string countdirectories {
            get {
                return ResourceManager.GetString("countdirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Arquivos:.
        /// </summary>
        internal static string countfiles {
            get {
                return ResourceManager.GetString("countfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Entrada mais antiga:.
        /// </summary>
        internal static string countfirst {
            get {
                return ResourceManager.GetString("countfirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Arquivo atual.
        /// </summary>
        internal static string currentfile {
            get {
                return ResourceManager.GetString("currentfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Grade de dados.
        /// </summary>
        internal static string datagrid {
            get {
                return ResourceManager.GetString("datagrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data.
        /// </summary>
        internal static string date {
            get {
                return ResourceManager.GetString("date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Diretório.
        /// </summary>
        internal static string directory {
            get {
                return ResourceManager.GetString("directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Arvore de diretórios.
        /// </summary>
        internal static string directorytree {
            get {
                return ResourceManager.GetString("directorytree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Disco.
        /// </summary>
        internal static string drive {
            get {
                return ResourceManager.GetString("drive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Entrar no diretório da entrada.
        /// </summary>
        internal static string enterdir {
            get {
                return ResourceManager.GetString("enterdir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Mostrar informações do arquivo.
        /// </summary>
        internal static string entryinfo {
            get {
                return ResourceManager.GetString("entryinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Exportar.
        /// </summary>
        internal static string export {
            get {
                return ResourceManager.GetString("export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Arquivo.
        /// </summary>
        internal static string file {
            get {
                return ResourceManager.GetString("file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Arquivo foi deletado.
        /// </summary>
        internal static string filedeleted {
            get {
                return ResourceManager.GetString("filedeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Identificador do arquivo.
        /// </summary>
        internal static string fileid {
            get {
                return ResourceManager.GetString("fileid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Formato.
        /// </summary>
        internal static string format {
            get {
                return ResourceManager.GetString("format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Seleção de disco.
        /// </summary>
        internal static string formdrive {
            get {
                return ResourceManager.GetString("formdrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Informações da entrada.
        /// </summary>
        internal static string formentryinfo {
            get {
                return ResourceManager.GetString("formentryinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Informação.
        /// </summary>
        internal static string info {
            get {
                return ResourceManager.GetString("info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Lingua.
        /// </summary>
        internal static string language {
            get {
                return ResourceManager.GetString("language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Ideia para o projeto, traduziu razões.
        /// </summary>
        internal static string lordyzagatdesc {
            get {
                return ResourceManager.GetString("lordyzagatdesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome.
        /// </summary>
        internal static string name {
            get {
                return ResourceManager.GetString("name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a OpenByFileId Win32 API compatibilização para C#.
        /// </summary>
        internal static string nolandesc {
            get {
                return ResourceManager.GetString("nolandesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Desenvolvedor principal.
        /// </summary>
        internal static string poneidesc {
            get {
                return ResourceManager.GetString("poneidesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Razão.
        /// </summary>
        internal static string reason {
            get {
                return ResourceManager.GetString("reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Raiz.
        /// </summary>
        internal static string root {
            get {
                return ResourceManager.GetString("root", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Escanear.
        /// </summary>
        internal static string scan {
            get {
                return ResourceManager.GetString("scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Pesquisar.
        /// </summary>
        internal static string search {
            get {
                return ResourceManager.GetString("search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Selecionar.
        /// </summary>
        internal static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a NTFS UsnJournal Win32 API compatibilização para C#.
        /// </summary>
        internal static string skipperdesc {
            get {
                return ResourceManager.GetString("skipperdesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O programa não conseguiu manejar o disco selecionado, para consultar o estado atual do journal..
        /// </summary>
        internal static string statusdesc_1 {
            get {
                return ResourceManager.GetString("statusdesc-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O programa não conseguiu consultar o estado atual do journal. Certifique-se de que o disco selecionado tenha o journal habilitado..
        /// </summary>
        internal static string statusdesc_2 {
            get {
                return ResourceManager.GetString("statusdesc-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O programa não conseguiu chamar o DeviceIoControl corretamente para retornar todos as entradas do journal do disco..
        /// </summary>
        internal static string statusdesc_3 {
            get {
                return ResourceManager.GetString("statusdesc-3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O programa não conseguiu resolver as identificações dos arquivos corretamente. Algo está bloqueando o programa?.
        /// </summary>
        internal static string statusdesc_4 {
            get {
                return ResourceManager.GetString("statusdesc-4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O programa não conseguiu analisar corretamente as entradas do journal corretamente. Isto pode ser culpa do programa..
        /// </summary>
        internal static string statusdesc_5 {
            get {
                return ResourceManager.GetString("statusdesc-5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Por favor, selecione o disco desejado e incie a filtragem do journal..
        /// </summary>
        internal static string statusdesc0 {
            get {
                return ResourceManager.GetString("statusdesc0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Para consultar o journal, temos que ter certeza de que podemos criar handles sem problemas..
        /// </summary>
        internal static string statusdesc1 {
            get {
                return ResourceManager.GetString("statusdesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Precisamos consultar o estado atual do journal para obter seus valores..
        /// </summary>
        internal static string statusdesc2 {
            get {
                return ResourceManager.GetString("statusdesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Chamando de DeviceIoControl para nos dar todas as entradas do ID do journal atual..
        /// </summary>
        internal static string statusdesc3 {
            get {
                return ResourceManager.GetString("statusdesc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Os ID&apos;s dos arquivos não são caminhos legíveis por humanos, então precisamos resolver todos os possíveis..
        /// </summary>
        internal static string statusdesc4 {
            get {
                return ResourceManager.GetString("statusdesc4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Transformando todas as entradas de journal em classes que modificaremos e consultaremos mais tarde..
        /// </summary>
        internal static string statusdesc5 {
            get {
                return ResourceManager.GetString("statusdesc5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Selecione um tipo de layout para visualizar os dados coletados. Cada um mostrará os dados de uma maneira diferente..
        /// </summary>
        internal static string statusdesc6 {
            get {
                return ResourceManager.GetString("statusdesc6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Transformando entradas em fileiras....
        /// </summary>
        internal static string statusgrid0 {
            get {
                return ResourceManager.GetString("statusgrid0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Adicionando fileiras à grade....
        /// </summary>
        internal static string statusgrid1 {
            get {
                return ResourceManager.GetString("statusgrid1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível manejar o disco selecionado..
        /// </summary>
        internal static string statustitle_1 {
            get {
                return ResourceManager.GetString("statustitle-1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível retornar o estado atual do journal..
        /// </summary>
        internal static string statustitle_2 {
            get {
                return ResourceManager.GetString("statustitle-2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível consultar as entradas do journal..
        /// </summary>
        internal static string statustitle_3 {
            get {
                return ResourceManager.GetString("statustitle-3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível resolver os ID&apos;s..
        /// </summary>
        internal static string statustitle_4 {
            get {
                return ResourceManager.GetString("statustitle-4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível analisar as entradas..
        /// </summary>
        internal static string statustitle_5 {
            get {
                return ResourceManager.GetString("statustitle-5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Aguardando entrada....
        /// </summary>
        internal static string statustitle0 {
            get {
                return ResourceManager.GetString("statustitle0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Getting handle to volume....
        /// </summary>
        internal static string statustitle1 {
            get {
                return ResourceManager.GetString("statustitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Obtendo o estado atual do journal....
        /// </summary>
        internal static string statustitle2 {
            get {
                return ResourceManager.GetString("statustitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Consultando as entradas do journal....
        /// </summary>
        internal static string statustitle3 {
            get {
                return ResourceManager.GetString("statustitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Resolvendo identificações de arquivos....
        /// </summary>
        internal static string statustitle4 {
            get {
                return ResourceManager.GetString("statustitle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Analisando entradas....
        /// </summary>
        internal static string statustitle5 {
            get {
                return ResourceManager.GetString("statustitle5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tudo pronto!.
        /// </summary>
        internal static string statustitle6 {
            get {
                return ResourceManager.GetString("statustitle6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Espaço total livre.
        /// </summary>
        internal static string totalfreespace {
            get {
                return ResourceManager.GetString("totalfreespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Espaço total.
        /// </summary>
        internal static string totalsize {
            get {
                return ResourceManager.GetString("totalsize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Tipo.
        /// </summary>
        internal static string type {
            get {
                return ResourceManager.GetString("type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Substituição de dados,Extensão de dados,Truncagem de dados,Substituição de dados nomeados,Extensão de dados nomeados,Truncagem de dados nomeados,Criação de arquivo,Exclusão de arquivo,Alteração de EA,Alteração de segurança,Renomear: nome antigo,Renomear: novo nome,Alteração de indexável,Alteração de informações básicas,Alteração de link físico,Alteração de compressão,Alteração de criptografia,Alteração de ID de objeto,Alteração do ponto de nova análise,Alteração de fluxo,Fechar.
        /// </summary>
        internal static string usnreasons {
            get {
                return ResourceManager.GetString("usnreasons", resourceCulture);
            }
        }
    }
}
